//#include "mbed.h"
#define MOTOR_X D4
#define MOTOR_Y D5
#define MOTOR_Z D6
#define EN_X PC_8
#define EN_Y D2
#define EN_Z D3
#define DIR_X D7
#define DIR_Y D8
#define DIR_Z D9
#define FDC_XUP D10
#define FDC_XDWN D11
#define FDC_YUP D12
#define FDC_YDWN D13
#define FDC_ZUP D14
#define FDC_ZDWN PC_10
#define BTN_XUP PC_12
#define BTN_XDWN PA_13
#define BTN_YUP PA_14
#define BTN_YDWN PA_15
#define BTN_ZUP PC_13
#define BTN_ZDWN PC_11
#define EMER_1 PC_15
#define EMER_2 PC_6
#define LCD_EN PC_5
#define LCD_RS PA_12
#define LCD_D4 PA_11
#define LCD_D5 PB_12
#define LCD_D6 PB_11
#define LCD_D7 PB_2
#define BTN_ENTER PB_1
#define BNT_SPEED1 PB_15
#define BTN_SPEED2 PB_14
#define BTN_SPEED3 PB_13
#define PIPETA PC_4
#define LAMP PC_0

